name: Tests

on:
  push:            # каждый push
    branches: [ main ]
  pull_request:    # или PR
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-qt pytest-cov

      - name: Run tests
        run: |
          pytest --cov=attendance --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to badge (опция)
        uses: actions/upload-artifact@v3
        with:
          name: coverage-xml
          path: coverage.xml
